import base64
from io import BytesIO
from datetime import datetime
from pathlib import Path
import re
from fpdf import FPDF

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    HAS_REPORTLAB = True
except Exception:
    HAS_REPORTLAB = False


class PDFService:
    DEFAULT_BULLETIN_TEXT = 'Health advisory generated with available epidemiological indicators. Follow local AYUSH guidance and monitor symptoms.'

    def _sanitize(self, text: str) -> str:
        cleaned = re.sub(r'[^\x20-\x7E\n\r\t]', '', str(text))
        return cleaned.strip()

    def _safe_text(self, text: str | None, default: str) -> str:
        sanitized = self._sanitize(text or '')
        return sanitized if sanitized else default

    def _safe_lines(self, lines: list[str] | None, default: str) -> list[str]:
        cleaned = [self._sanitize(item) for item in (lines or []) if self._sanitize(item)]
        return cleaned if cleaned else [default]

    def _save_to_base64(self, pdf: FPDF, filename: str) -> str:
        out_dir = Path('/tmp')
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / filename
        pdf.output(str(out_path))
        return base64.b64encode(out_path.read_bytes()).decode('utf-8')

    def generate_bulletin(
        self,
        district_name: str,
        risk_level: str,
        risk_score: int,
        top_conditions: list[str],
        xai_reasons: list[str],
        seasonal_advisory: str,
        bulletin_text: str = '',
    ) -> str:
        district_name = self._safe_text(district_name, 'Unknown district')
        risk_level = self._safe_text(risk_level, 'medium')
        safe_conditions = self._safe_lines(top_conditions, 'General preventive care')
        safe_reasons = self._safe_lines(xai_reasons, 'Epidemiological and environmental indicators suggest moderate vigilance.')
        safe_advisory = self._safe_text(seasonal_advisory, 'Maintain balanced routine, hydration, and timely rest.')
        safe_bulletin = self._safe_text(bulletin_text, self.DEFAULT_BULLETIN_TEXT)

        if HAS_REPORTLAB:
            buffer = BytesIO()
            doc = SimpleDocTemplate(
                buffer,
                pagesize=A4,
                leftMargin=36,
                rightMargin=36,
                topMargin=36,
                bottomMargin=36,
            )
            styles = getSampleStyleSheet()
            story = [
                Paragraph('PrakritiOS AYUSH Health Bulletin', styles['Title']),
                Spacer(1, 8),
                Paragraph(self._safe_text(f'District: {district_name} | Date: {datetime.utcnow().date()}', 'District summary unavailable'), styles['Normal']),
                Spacer(1, 8),
                Paragraph(self._safe_text(f'Risk: {risk_level.upper()} ({risk_score}/100)', 'Risk: MEDIUM (50/100)'), styles['Heading3']),
                Spacer(1, 6),
                Paragraph('Top Conditions', styles['Heading3']),
            ]
            for condition in safe_conditions:
                story.append(Paragraph(f'• {condition}', styles['Normal']))

            story.extend([Spacer(1, 8), Paragraph('AI Reasoning', styles['Heading3'])])
            for index, reason in enumerate(safe_reasons, start=1):
                story.append(Paragraph(f'{index}. {reason}', styles['Normal']))

            story.extend([
                Spacer(1, 8),
                Paragraph('Seasonal Advisory', styles['Heading3']),
                Paragraph(safe_advisory, styles['Normal']),
                Spacer(1, 8),
                Paragraph('Bulletin Summary', styles['Heading3']),
                Paragraph(safe_bulletin, styles['Normal']),
                Spacer(1, 10),
                Paragraph('Generated by PrakritiOS AI', styles['Italic']),
            ])
            doc.build(story)
            return base64.b64encode(buffer.getvalue()).decode('utf-8')

        pdf = FPDF()
        pdf.set_margins(15, 15, 15)
        pdf.add_page()

        pdf.set_font('Arial', 'B', 18)
        pdf.cell(0, 10, self._sanitize('PrakritiOS AYUSH Health Bulletin'), ln=1, align='C')
        pdf.set_font('Arial', '', 11)
        pdf.cell(0, 8, self._sanitize(f'District: {district_name} | Date: {datetime.utcnow().date()}'), ln=1)

        pdf.set_fill_color(220, 235, 220)
        pdf.rect(15, pdf.get_y(), 180, 10, 'F')
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, self._sanitize(f'Risk: {risk_level.upper()} ({risk_score}/100)'), ln=1)

        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 8, 'Top Conditions', ln=1)
        pdf.set_font('Arial', '', 11)
        for condition in safe_conditions:
            pdf.cell(0, 7, self._sanitize(f'- {condition}'), ln=1)

        pdf.set_fill_color(230, 240, 250)
        pdf.rect(15, pdf.get_y(), 180, 9, 'F')
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 9, 'AI Reasoning', ln=1)
        pdf.set_font('Arial', '', 11)
        for index, reason in enumerate(safe_reasons, start=1):
            pdf.multi_cell(0, 6, self._sanitize(f'{index}. {reason}'))

        pdf.set_fill_color(245, 238, 220)
        pdf.rect(15, pdf.get_y(), 180, 9, 'F')
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 9, 'Seasonal Advisory', ln=1)
        pdf.set_font('Arial', '', 11)
        pdf.multi_cell(0, 6, self._sanitize(safe_advisory))

        pdf.set_x(pdf.l_margin)
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 8, 'Bulletin Summary', ln=1)
        pdf.set_font('Arial', '', 11)
        pdf.multi_cell(0, 6, self._sanitize(safe_bulletin))

        pdf.set_y(-20)
        pdf.set_font('Arial', 'I', 9)
        pdf.cell(0, 10, self._sanitize('Generated by PrakritiOS AI'), align='C')
        return self._save_to_base64(pdf, 'bulletin.pdf')

    def generate_arogya_report(self, user_name: str, dosha: str, history: list[dict], risk_score: float = 50.0) -> str:
        pdf = FPDF()
        pdf.set_margins(15, 15, 15)
        pdf.add_page()
        pdf.set_font('Arial', 'B', 17)
        pdf.cell(0, 10, self._sanitize('Arogya Granth - Personal Health Scripture'), ln=1, align='C')

        pdf.set_fill_color(228, 236, 245)
        pdf.rect(15, pdf.get_y(), 180, 22, 'F')
        pdf.set_font('Arial', 'B', 11)
        pdf.cell(0, 7, self._sanitize(f'Name: {user_name}'), ln=1)
        pdf.cell(0, 7, self._sanitize(f'Dominant Dosha: {dosha}'), ln=1)
        pdf.cell(0, 7, self._sanitize(f'Constitutional Risk: {round(risk_score, 1)}/100'), ln=1)

        pdf.ln(3)
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 8, 'Health Journey', ln=1)
        pdf.set_font('Arial', '', 10)
        pdf.cell(50, 7, 'Date', 1)
        pdf.cell(90, 7, 'Symptoms', 1)
        pdf.cell(50, 7, 'Top Herb', 1, ln=1)

        for row in history[:8]:
            symptoms = row.get('symptoms', [])
            if isinstance(symptoms, dict):
                symptoms = symptoms.get('items', [])
            herb = row.get('response', {}).get('herbs', [{'name': 'N/A'}])[0].get('name', 'N/A') if isinstance(row.get('response'), dict) else 'N/A'
            pdf.cell(50, 7, self._sanitize(str(row.get('date', 'NA'))[:10]), 1)
            pdf.cell(90, 7, self._sanitize(', '.join(symptoms)[:45]), 1)
            pdf.cell(50, 7, self._sanitize(herb[:25]), 1, ln=1)

        pdf.ln(3)
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 8, 'Dosha Balance', ln=1)
        bars = {
            'V': 10 if dosha.lower() == 'vata' else 6,
            'P': 10 if dosha.lower() == 'pitta' else 6,
            'K': 10 if dosha.lower() == 'kapha' else 6,
        }
        pdf.set_font('Arial', '', 11)
        pdf.cell(0, 7, self._sanitize(f"V: {'#' * bars['V']}"), ln=1)
        pdf.cell(0, 7, self._sanitize(f"P: {'#' * bars['P']}"), ln=1)
        pdf.cell(0, 7, self._sanitize(f"K: {'#' * bars['K']}"), ln=1)

        recommendations = {
            'vata': 'Keep routine stable, prefer warm meals, and use calming pranayama daily.',
            'pitta': 'Use cooling foods, avoid excess spice, and include evening relaxation.',
            'kapha': 'Increase daily movement, avoid heavy cold foods, and use warming spices.',
        }
        pdf.ln(2)
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 8, 'Lifestyle Recommendation', ln=1)
        pdf.set_font('Arial', '', 11)
        pdf.multi_cell(0, 6, self._sanitize(recommendations.get(dosha.lower(), recommendations['vata'])))

        pdf.set_y(-20)
        pdf.set_font('Arial', 'I', 9)
        pdf.cell(0, 10, self._sanitize('Seal of AYUSH AI'), align='C')
        return self._save_to_base64(pdf, 'arogya_report.pdf')
